// <auto-generated />
using System;
using Arsoude_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arsoude_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("Arsoude_Backend.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrailId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("userHasCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrailId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("TrailId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrailId");

                    b.ToTable("Coordinates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 45.559601999999998,
                            Longitude = -73.580235999999999
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 45.671821999999999,
                            Longitude = -73.526653999999994
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 48.909387000000002,
                            Longitude = -75.818077000000002
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 48.806409000000002,
                            Longitude = -75.914644999999993
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 48.969093000000001,
                            Longitude = -76.906711999999999
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 48.925913999999999,
                            Longitude = -76.893321999999998
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 45.928130000000003,
                            Longitude = -74.044250000000005
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 45.923990000000003,
                            Longitude = -74.041640000000001
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 45.892060000000001,
                            Longitude = -74.159469999999999
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 46.341439999999999,
                            Longitude = -74.267880000000005
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 48.568269999999998,
                            Longitude = -64.306809999999999
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 48.574312999999997,
                            Longitude = -64.352936999999997
                        },
                        new
                        {
                            Id = 13,
                            Latitude = 48.568269999999998,
                            Longitude = -64.306809999999999
                        },
                        new
                        {
                            Id = 14,
                            Latitude = 48.808650999999998,
                            Longitude = -64.220134000000002
                        },
                        new
                        {
                            Id = 15,
                            Latitude = 49.227136000000002,
                            Longitude = -65.920732999999998
                        },
                        new
                        {
                            Id = 16,
                            Latitude = 49.193142000000002,
                            Longitude = -65.902365000000003
                        },
                        new
                        {
                            Id = 17,
                            Latitude = 51.545589999999997,
                            Longitude = -69.132334999999998
                        },
                        new
                        {
                            Id = 18,
                            Latitude = 51.160510000000002,
                            Longitude = -69.023844999999994
                        },
                        new
                        {
                            Id = 19,
                            Latitude = 51.545589999999997,
                            Longitude = -69.132334999999998
                        },
                        new
                        {
                            Id = 20,
                            Latitude = 51.160510000000002,
                            Longitude = -69.023844999999994
                        },
                        new
                        {
                            Id = 21,
                            Latitude = 51.545589999999997,
                            Longitude = -69.132334999999998
                        },
                        new
                        {
                            Id = 22,
                            Latitude = 51.160510000000002,
                            Longitude = -69.023844999999994
                        },
                        new
                        {
                            Id = 23,
                            Latitude = 54.012407000000003,
                            Longitude = -82.219065999999998
                        },
                        new
                        {
                            Id = 24,
                            Latitude = 55.002626999999997,
                            Longitude = -82.279490999999993
                        },
                        new
                        {
                            Id = 25,
                            Latitude = 62.838535,
                            Longitude = -91.898669999999996
                        },
                        new
                        {
                            Id = 26,
                            Latitude = 63.303736000000001,
                            Longitude = -90.769824999999997
                        },
                        new
                        {
                            Id = 27,
                            Latitude = 74.022659000000004,
                            Longitude = -41.820591999999998
                        },
                        new
                        {
                            Id = 28,
                            Latitude = 75.560384999999997,
                            Longitude = -31.515416999999999
                        },
                        new
                        {
                            Id = 29,
                            Latitude = 68.110088000000005,
                            Longitude = 23.315586
                        },
                        new
                        {
                            Id = 30,
                            Latitude = 67.879562000000007,
                            Longitude = 23.189229000000001
                        },
                        new
                        {
                            Id = 31,
                            Latitude = 69.151650000000004,
                            Longitude = 106.003671
                        },
                        new
                        {
                            Id = 32,
                            Latitude = 59.895603000000001,
                            Longitude = 104.905038
                        },
                        new
                        {
                            Id = 33,
                            Latitude = 29.240485,
                            Longitude = -114.689688
                        },
                        new
                        {
                            Id = 34,
                            Latitude = 23.807555000000001,
                            Longitude = -110.657706
                        },
                        new
                        {
                            Id = 35,
                            Latitude = -11.490477,
                            Longitude = -37.386364
                        },
                        new
                        {
                            Id = 36,
                            Latitude = -12.838269,
                            Longitude = -38.243298000000003
                        },
                        new
                        {
                            Id = 37,
                            Latitude = -18.224066000000001,
                            Longitude = 49.397387000000002
                        },
                        new
                        {
                            Id = 38,
                            Latitude = -20.637858000000001,
                            Longitude = 48.529466999999997
                        },
                        new
                        {
                            Id = 39,
                            Latitude = 10.71109,
                            Longitude = 51.120646999999998
                        },
                        new
                        {
                            Id = 40,
                            Latitude = 6.6828969999999996,
                            Longitude = 49.088177000000002
                        },
                        new
                        {
                            Id = 41,
                            Latitude = 38.587606999999998,
                            Longitude = 128.37471199999999
                        },
                        new
                        {
                            Id = 42,
                            Latitude = 38.404083,
                            Longitude = 128.45505
                        });
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrailId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Hike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrailId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrailId");

                    b.HasIndex("UserId");

                    b.ToTable("Hikes");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.ImageTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrailId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrailId");

                    b.ToTable("TrailImages");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextLevelExperience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviousLevelExperience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.NotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsTurnedOn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Trail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int>("EndingCoordinatesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("StartingCoordinatesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isPublic")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndingCoordinatesId");

                    b.HasIndex("StartingCoordinatesId");

                    b.HasIndex("UserId");

                    b.ToTable("Trails");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Description = "Une randonnée pittoresque à travers une forêt luxuriante où les oiseaux chantent et les rivières murmurent.",
                            EndingCoordinatesId = 2,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/test.jpg?alt=media&token=16218832-5af7-4544-add2-a384190f4a5a",
                            Location = "Parc National de la Forêt Verte",
                            Name = "Sentier de la Forêt Enchantée",
                            OwnerId = 1,
                            StartingCoordinatesId = 1,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 0,
                            isPublic = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Une aventure difficile menant au sommet d'une montagne majestueuse offrant une vue imprenable sur la vallée ci-dessous.",
                            EndingCoordinatesId = 4,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/49777868268_2dcd6e6d85_o_603e508e5d170.jpg?alt=media&token=ddb83ad6-6384-4c61-9410-c7ec2809e020",
                            Location = "Parc National des Montagnes Escarpées",
                            Name = "Escapade au Sommet",
                            OwnerId = 1,
                            StartingCoordinatesId = 3,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = true
                        },
                        new
                        {
                            Id = 31,
                            Description = "Une randonnée enchanteresse le long de plusieurs cascades étincelantes, où l'eau scintille au soleil et crée un spectacle magique. Ce sentier offre une expérience sensorielle unique avec le bruit apaisant de l'eau qui coule, les reflets chatoyants et la fraîcheur de l'air pur. Vous serez transporté dans un monde de beauté naturelle et de tranquillité.",
                            EndingCoordinatesId = 6,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/640px-Tim_Hortons.jpg?alt=media&token=5b7707d7-8f0b-45fb-8029-e6192291c10b",
                            Location = "Parc National des Cascades Étincelantes",
                            Name = "Sentier des Cascades Étincelantes",
                            OwnerId = 1,
                            StartingCoordinatesId = 5,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = true
                        },
                        new
                        {
                            Id = 32,
                            Description = "Une promenade pittoresque à travers de vastes champs de fleurs colorées, où vous pourrez vous imprégner des parfums enivrants et des couleurs éclatantes de la nature. Ce sentier offre une expérience visuelle et olfactive unique, avec des vues panoramiques sur les champs à perte de vue et une ambiance paisible qui invite à la détente et à la contemplation.",
                            EndingCoordinatesId = 8,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/646ecba4d5310c7256b400e4_iphigenie-carte-IGN.jpeg?alt=media&token=a1285d82-eb22-4c38-b509-3718bcecc23d",
                            Location = "Champs de Fleurs en Fleur",
                            Name = "Promenade des Champs de Fleurs",
                            OwnerId = 1,
                            StartingCoordinatesId = 7,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = true
                        },
                        new
                        {
                            Id = 33,
                            Description = "Une randonnée jusqu'à un pittoresque lac de montagne, niché au creux des sommets enneigés et entouré d'une nature sauvage et préservée. Ce sentier offre des vues panoramiques spectaculaires sur les montagnes environnantes et une atmosphère paisible et relaxante près de l'eau cristalline du lac.",
                            EndingCoordinatesId = 10,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/A-Sea-Of-Clouds-And-Mountains.jpg?alt=media&token=18d7ba11-bb99-4b18-97dc-c0f5c9c59999",
                            Location = "Lac de Montagne Tranquille",
                            Name = "Escapade au Lac de Montagne",
                            OwnerId = 1,
                            StartingCoordinatesId = 9,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 0,
                            isPublic = true
                        },
                        new
                        {
                            Id = 34,
                            Description = "Une aventure à travers les ruines anciennes d'une civilisation disparue, où vous pourrez découvrir l'histoire fascinante de ce site archéologique. Ce sentier offre une expérience immersive dans le passé, avec des vestiges bien préservés et des paysages à couper le souffle qui témoignent de la grandeur passée de cette civilisation.",
                            EndingCoordinatesId = 12,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/istockphoto-1369171053-612x612.jpg?alt=media&token=5506f8ac-46cd-4023-89fc-e7b0ac18909c",
                            Location = "Site Archéologique des Ruines Anciennes",
                            Name = "Sentier des Ruines Anciennes",
                            OwnerId = 1,
                            StartingCoordinatesId = 11,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 0,
                            isPublic = true
                        },
                        new
                        {
                            Id = 35,
                            Description = "Une randonnée le long de falaises côtières majestueuses, offrant des vues spectaculaires sur l'océan et les côtes rocheuses. Ce sentier offre une expérience unique en bord de mer, avec des panoramas à couper le souffle et une ambiance maritime rafraîchissante.",
                            EndingCoordinatesId = 14,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/mountainBackground.jpg?alt=media&token=56efecc5-c94b-4927-9d19-23f5def22854",
                            Location = "Falaises Côtières",
                            Name = "Randonnée des Falaises Côtières",
                            OwnerId = 1,
                            StartingCoordinatesId = 13,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 0,
                            isPublic = true
                        },
                        new
                        {
                            Id = 36,
                            Description = "Une balade à travers une vallée paisible et endormie, où le temps semble s'être arrêté. Ce sentier offre une expérience tranquille en pleine nature, avec des paysages pittoresques et une ambiance relaxante qui invite à la contemplation.",
                            EndingCoordinatesId = 16,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/photo-aerienne.jpg?alt=media&token=c1bc1d71-979c-4bc8-ba7e-7c4c7cc15434",
                            Location = "Vallée Endormie",
                            Name = "Sentier de la Vallée Endormie",
                            OwnerId = 1,
                            StartingCoordinatesId = 15,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 0,
                            isPublic = true
                        },
                        new
                        {
                            Id = 37,
                            Description = "Une randonnée jusqu'au sommet d'un pic vertigineux, offrant des vues à couper le souffle sur les vallées et les montagnes environnantes. Ce sentier offre une expérience exaltante pour les amateurs de sensations fortes, avec des panoramas spectaculaires et une montée stimulante.",
                            EndingCoordinatesId = 18,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/rando.jpg?alt=media&token=fc58456a-ce4d-42b1-94d1-bf6a6ecbe5b4",
                            Location = "Pic Vertigineux",
                            Name = "Randonnée du Pic Vertigineux",
                            OwnerId = 1,
                            StartingCoordinatesId = 17,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = true
                        },
                        new
                        {
                            Id = 38,
                            Description = "Une balade le long de plusieurs chutes mystiques, cachées au cœur d'une forêt luxuriante. Ce sentier offre une expérience enchantée, avec des cascades paisibles et des paysages magiques qui émerveilleront les sens.",
                            EndingCoordinatesId = 20,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/randonnee-en-france-dans-les-gorges-du-verdon.jpg?alt=media&token=f1c7f80a-3d7d-4606-b97a-c24d587070e7",
                            Location = "Forêt des Chutes Mystiques",
                            Name = "Chemin des Chutes Mystiques",
                            OwnerId = 1,
                            StartingCoordinatesId = 19,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = true
                        },
                        new
                        {
                            Id = 39,
                            Description = "Une randonnée jusqu'à un magnifique lac de cristal, dont les eaux claires reflètent les montagnes environnantes. Ce sentier offre une expérience rafraîchissante en plein air, avec la possibilité de se baigner dans les eaux cristallines du lac.",
                            EndingCoordinatesId = 22,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/test.jpg?alt=media&token=16218832-5af7-4544-add2-a384190f4a5a",
                            Location = "Lac de Cristal",
                            Name = "Randonnée du Lac de Cristal",
                            OwnerId = 1,
                            StartingCoordinatesId = 21,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = true
                        },
                        new
                        {
                            Id = 40,
                            Description = "Une randonnée à travers un canyon étincelant, où la lumière du soleil se reflète sur les parois rocheuses pour créer un spectacle scintillant. Ce sentier offre une expérience visuelle saisissante, avec des jeux de lumière magiques et des formations rocheuses uniques.",
                            EndingCoordinatesId = 24,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/t%C3%A9l%C3%A9chargement%20(2).jfif?alt=media&token=85a8dbbb-0960-4ed5-9628-869dcc977adb",
                            Location = "Canyon Étincelant",
                            Name = "Sentier du Canyon Étincelant",
                            OwnerId = 1,
                            StartingCoordinatesId = 23,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = true
                        },
                        new
                        {
                            Id = 41,
                            Description = "Une balade à travers des jardins enchanteurs, où vous pourrez admirer une grande variété de plantes exotiques et de fleurs colorées. Ce sentier offre une expérience botanique unique, avec des jardins bien entretenus et une ambiance paisible qui invite à la contemplation.",
                            EndingCoordinatesId = 26,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/t%C3%A9l%C3%A9chargement.jpg?alt=media&token=c22f1408-24e1-49e4-9afa-d245a5c09b88",
                            Location = "Jardins Enchantés",
                            Name = "Promenade des Jardins Enchantés",
                            OwnerId = 1,
                            StartingCoordinatesId = 25,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 0,
                            isPublic = false
                        },
                        new
                        {
                            Id = 42,
                            Description = "Une randonnée épique jusqu'au sommet d'une montagne enneigée, offrant des vues à couper le souffle sur les paysages alpins. Ce sentier offre une expérience alpine authentique, avec des vues panoramiques sur les montagnes enneigées et une ambiance hivernale magique.",
                            EndingCoordinatesId = 28,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/uvqqzh20rqargzgyuqzv.jpg?alt=media&token=b13cf228-e7e9-409b-b9b7-919889e42a96",
                            Location = "Sommet Enneigé",
                            Name = "Randonnée du Sommet Enneigé",
                            OwnerId = 1,
                            StartingCoordinatesId = 27,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 0,
                            isPublic = false
                        },
                        new
                        {
                            Id = 43,
                            Description = "Une promenade à travers des marais brumeux, où l'air est chargé d'humidité et la lumière filtre à travers le brouillard. Ce sentier offre une expérience mystérieuse et immersive dans les marais, avec des paysages enveloppés de brume et une ambiance envoûtante.",
                            EndingCoordinatesId = 30,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/test.jpg?alt=media&token=16218832-5af7-4544-add2-a384190f4a5a",
                            Location = "Marais Brumeux",
                            Name = "Sentier des Marais Brumeux",
                            OwnerId = 1,
                            StartingCoordinatesId = 29,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 0,
                            isPublic = false
                        },
                        new
                        {
                            Id = 45,
                            Description = "Une randonnée jusqu'à une cascade éternelle, dont les eaux coulent continuellement et offrent un spectacle apaisant. Ce sentier offre une expérience rafraîchissante en plein air, avec la possibilité de se détendre près de la cascade et d'admirer sa beauté intemporelle.",
                            EndingCoordinatesId = 32,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/test.jpg?alt=media&token=16218832-5af7-4544-add2-a384190f4a5a",
                            Location = "Cascade Éternelle",
                            Name = "Sentier de la Cascade Éternelle",
                            OwnerId = 1,
                            StartingCoordinatesId = 31,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = false
                        },
                        new
                        {
                            Id = 46,
                            Description = "Une balade paisible autour d'un lac serein, où vous pourrez profiter de la tranquillité de l'eau et observer la faune locale. Ce sentier offre une expérience relaxante en plein air, avec des vues pittoresques sur le lac et une ambiance calme qui invite à la méditation.",
                            EndingCoordinatesId = 34,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/test.jpg?alt=media&token=16218832-5af7-4544-add2-a384190f4a5a",
                            Location = "Lac Serein",
                            Name = "Promenade du Lac Serein",
                            OwnerId = 1,
                            StartingCoordinatesId = 33,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = false
                        },
                        new
                        {
                            Id = 47,
                            Description = "Une randonnée à travers les montagnes miroir, où les sommets reflètent parfaitement le ciel et les nuages. Ce sentier offre une expérience visuelle spectaculaire, avec des panoramas époustouflants et des paysages qui semblent sortis d'un rêve.",
                            EndingCoordinatesId = 36,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/test.jpg?alt=media&token=16218832-5af7-4544-add2-a384190f4a5aG",
                            Location = "Montagnes Miroir",
                            Name = "Randonnée des Montagnes Miroir",
                            OwnerId = 1,
                            StartingCoordinatesId = 35,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = false
                        },
                        new
                        {
                            Id = 48,
                            Description = "Une balade en fin de journée pour admirer le coucher de soleil sur l'horizon, offrant des couleurs chaudes et des reflets dorés sur l'eau. Ce sentier offre une expérience magique en plein air, avec des vues panoramiques sur le ciel coloré et une ambiance paisible qui invite à la contemplation.",
                            EndingCoordinatesId = 38,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/test.jpg?alt=media&token=16218832-5af7-4544-add2-a384190f4a5a",
                            Location = "Coucher de Soleil",
                            Name = "Sentier du Coucher de Soleil",
                            OwnerId = 1,
                            StartingCoordinatesId = 37,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 0,
                            isPublic = false
                        },
                        new
                        {
                            Id = 49,
                            Description = "Une randonnée épique à travers un canyon profond, où les parois rocheuses s'élèvent à des hauteurs vertigineuses de chaque côté. Ce sentier offre une expérience immersive dans la nature sauvage, avec des vues spectaculaires sur les falaises et les gorges.",
                            EndingCoordinatesId = 40,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/test.jpg?alt=media&token=16218832-5af7-4544-add2-a384190f4a5a",
                            Location = "Canyon Profond",
                            Name = "Randonnée du Canyon Profond",
                            OwnerId = 1,
                            StartingCoordinatesId = 39,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = false
                        },
                        new
                        {
                            Id = 50,
                            Description = "Une balade à travers une vallée mystique, où les brumes matinales créent une atmosphère envoûtante. Ce sentier offre une expérience magique en plein air, avec des paysages enveloppés de brume et une ambiance tranquille qui invite à la contemplation.",
                            EndingCoordinatesId = 42,
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/arsoudeserv.appspot.com/o/test.jpg?alt=media&token=16218832-5af7-4544-add2-a384190f4a5a",
                            Location = "Vallée des Brumes",
                            Name = "Sentier de la Vallée des Brumes",
                            OwnerId = 1,
                            StartingCoordinatesId = 41,
                            TotalCompletions = 0,
                            TotalRatings = 0,
                            Type = 1,
                            isPublic = false
                        });
                });

            modelBuilder.Entity("Arsoude_Backend.Models.TrailUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("VoteValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TrailRatingUser");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HouseNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MonthOfBirth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("TrailUsers");

                    b.HasData(
                        new
                        {
                            Id = 99,
                            AreaCode = "A1A 1A1",
                            FirstName = "Admin",
                            IdentityUserId = "11111111-1111-1111-1111-111111111111",
                            LastName = "Admin"
                        },
                        new
                        {
                            Id = 1,
                            AreaCode = "111 111",
                            FirstName = "Test",
                            IdentityUserId = "11111111-1111-1111-1111-111111111112",
                            LastName = "Test"
                        });
                });

            modelBuilder.Entity("Arsoude_Backend.Models.UserFavoriteTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrailId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavoriteTrails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111113",
                            ConcurrencyStamp = "bbecf30a-20f0-45f3-8101-f93f85f7de45",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "24252ac9-9714-4b9a-bbd4-7f8954fbf477",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECurr+LMVWK6ZcfKpAFWdQr6/JVtC5YpaXPSkLCmX1+cdQ+Yc3f3rDUtm3+ZsbPRUw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "81f0630b-dcd2-4158-b5f2-21d0d0b50eef",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111112",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b245f4ac-9042-447d-b251-261afa67e90a",
                            Email = "user@user.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@USER.COM",
                            NormalizedUserName = "USER@USER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKavuwCiAxgj4YYLWNJky8VLT8Dutjr0YP/dGPx/ZYxIh/Rg5YWJZySMIJP8mrUIZA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5daa531e-0f15-46c2-bc5c-bbfbc103d8da",
                            TwoFactorEnabled = false,
                            UserName = "user@user.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111111",
                            RoleId = "11111111-1111-1111-1111-111111111113"
                        },
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111112",
                            RoleId = "11111111-1111-1111-1111-111111111113"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Comments", b =>
                {
                    b.HasOne("Arsoude_Backend.Models.Trail", "Trail")
                        .WithMany("Comments")
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arsoude_Backend.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Coordinates", b =>
                {
                    b.HasOne("Arsoude_Backend.Models.Trail", null)
                        .WithMany("Coordinates")
                        .HasForeignKey("TrailId");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Event", b =>
                {
                    b.HasOne("Arsoude_Backend.Models.Trail", "Trail")
                        .WithMany()
                        .HasForeignKey("TrailId");

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Hike", b =>
                {
                    b.HasOne("Arsoude_Backend.Models.Trail", "Trail")
                        .WithMany()
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arsoude_Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.ImageTrail", b =>
                {
                    b.HasOne("Arsoude_Backend.Models.Trail", null)
                        .WithMany("ImageList")
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Level", b =>
                {
                    b.HasOne("Arsoude_Backend.Models.User", null)
                        .WithOne("Level")
                        .HasForeignKey("Arsoude_Backend.Models.Level", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arsoude_Backend.Models.NotificationSettings", b =>
                {
                    b.HasOne("Arsoude_Backend.Models.User", null)
                        .WithOne("NotificationSettings")
                        .HasForeignKey("Arsoude_Backend.Models.NotificationSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Trail", b =>
                {
                    b.HasOne("Arsoude_Backend.Models.Coordinates", "EndingCoordinates")
                        .WithMany()
                        .HasForeignKey("EndingCoordinatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arsoude_Backend.Models.Coordinates", "StartingCoordinates")
                        .WithMany()
                        .HasForeignKey("StartingCoordinatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arsoude_Backend.Models.User", null)
                        .WithMany("Trails")
                        .HasForeignKey("UserId");

                    b.Navigation("EndingCoordinates");

                    b.Navigation("StartingCoordinates");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.User", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.UserFavoriteTrail", b =>
                {
                    b.HasOne("Arsoude_Backend.Models.User", null)
                        .WithMany("FavouriteTrails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arsoude_Backend.Models.Trail", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Coordinates");

                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Arsoude_Backend.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FavouriteTrails");

                    b.Navigation("Level")
                        .IsRequired();

                    b.Navigation("NotificationSettings")
                        .IsRequired();

                    b.Navigation("Trails");
                });
#pragma warning restore 612, 618
        }
    }
}
